# Generated by Django 4.1.4 on 2022-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=250)),
                ('Imp_level_of_topic', models.CharField(max_length=250)),
                ('No_of_revision', models.IntegerField()),
            ],
        ),
    ]
