# Generated by Django 4.1.4 on 2022-12-26 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TODOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
